using System.Security.Cryptography;
using Microsoft.Extensions.Diagnostics.HealthChecks;

namespace BookingService.Api.Infrastructure.HealthChecks;

public class JwtConfigurationHealthCheck : IHealthCheck
{
    private readonly IConfiguration _configuration;

    public JwtConfigurationHealthCheck(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public Task<HealthCheckResult> CheckHealthAsync(
        HealthCheckContext context,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var jwtSettings = _configuration.GetSection("JwtSettings");
            var privateKey = jwtSettings["PrivateKey"];
            var publicKey = jwtSettings["PublicKey"];
            var issuer = jwtSettings["Issuer"];
            var audience = jwtSettings["Audience"];
            var accessTokenExpiryMinutes = jwtSettings["AccessTokenExpiryMinutes"];
            var refreshTokenExpiryDays = jwtSettings["RefreshTokenExpiryDays"];

            var issues = new List<string>();
            var isAutoGenerated = false;

            // Check if keys are auto-generated
            if (privateKey == "GENERATE" || string.IsNullOrWhiteSpace(privateKey))
            {
                isAutoGenerated = true;
            }
            else
            {
                // Validate RSA keys
                try
                {
                    var rsa = RSA.Create();
                    rsa.ImportFromPem(privateKey);
                }
                catch
                {
                    issues.Add("PrivateKey is not a valid PEM format");
                }
            }

            if (string.IsNullOrWhiteSpace(issuer))
                issues.Add("Issuer is missing");

            if (string.IsNullOrWhiteSpace(audience))
                issues.Add("Audience is missing");

            if (string.IsNullOrWhiteSpace(accessTokenExpiryMinutes))
                issues.Add("AccessTokenExpiryMinutes is missing");

            if (string.IsNullOrWhiteSpace(refreshTokenExpiryDays))
                issues.Add("RefreshTokenExpiryDays is missing");

            var data = new Dictionary<string, object>
            {
                { "issuer", issuer ?? "Not configured" },
                { "audience", audience ?? "Not configured" },
                { "access_token_expiry_minutes", accessTokenExpiryMinutes ?? "Not configured" },
                { "refresh_token_expiry_days", refreshTokenExpiryDays ?? "Not configured" },
                { "keys_auto_generated", isAutoGenerated },
                { "algorithm", "RS256" }
            };

            if (issues.Any())
            {
                return Task.FromResult(HealthCheckResult.Unhealthy(
                    $"JWT configuration issues: {string.Join(", ", issues)}",
                    data: data));
            }

            var message = isAutoGenerated 
                ? "JWT configuration is valid (RS256 - keys auto-generated for development)" 
                : "JWT configuration is valid (RS256)";

            return Task.FromResult(HealthCheckResult.Healthy(message, data));
        }
        catch (Exception ex)
        {
            return Task.FromResult(HealthCheckResult.Unhealthy(
                "JWT configuration health check failed",
                ex,
                data: new Dictionary<string, object>
                {
                    { "error", ex.Message }
                }));
        }
    }
}
